landingpage/urls.py
from django.urls import path

from .views import index, add_status
# delete_status

app_name = 'landingpage'

urlpatterns = [
    path('', index, name = 'index'),
    path('add_status/', add_status, name='add_status'),
    # path('delete_status/<int:status_id>', delete_status, name='delete_status'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
]

landingpage/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
	status = models.TextField(blank=False, max_length=300)
	created_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-created_at',)

landingpage/forms.py
from django import forms
from django.forms import Form

class Status_Form(forms.Form):

	error_messages = {
        'required': 'You should write your status.',
    }


	pos_attrs = {
		'type': 'text',
		'class':'form-control',
		'placeholder':'Write here... (300 characters)'

	}
	status = forms.CharField(required=True, widget=forms.Textarea(attrs=pos_attrs), max_length=300)
	

landingpage/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status



# Create your views here.

def index(request):
	
	response = {"status_form": Status_Form}
	statuses = Status.objects.all().values()
	response['status'] = statuses
	return render(request, 'landingpage.html', response)

def add_status(request):
	
	if(request.method == 'POST'):
		form = Status_Form(request.POST)
		if (form.is_valid()):
			status_fill = form.cleaned_data['status']
			status = Status(status = status_fill)
			status.save()
			
			
		return HttpResponseRedirect('/')
		

landingpage/templates/landingpage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <title>Hello ☀</title>
    <meta charset="utf-8"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
   
    <link rel="stylesheet" href="{% static 'css/landingpage.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,700i,900i&display=swap" rel="stylesheet"> 
</head>

<body>

		    
    <div style="text-align: center;">
    	<div class="display-1" style="font-weight: bold; font-style: italic; color: white; -webkit-text-stroke: 4px #7A6660;">Hi, How are you today?</div>
    	<div class=transbox>
    		<h1 style= "font-weight: light; font-style: italic">Share your <strong>stories</strong>, tell your <strong>feelings</strong>.</h1>


    	</div>
    </div>

    <div class="container">

		<div class="row">

    		<div class="col-lg-4 ">

			    <div  id="input-list" >
				    
				        <form id="form" method="POST" action="{% url 'landingpage:add_status' %}">
				            
				            {% csrf_token %}
				            {{ status_form.status }}
				            <input id="submit" type="submit" class="btn btn-lg btn-block btn-dark" value="Submit">
				            <br>
				        </form>
				    
				</div>
			</div>

			<div class="col-lg-8 " >

				<div class="myBox">
			
					<table class="table">
					    <tbody >

					    	{% if status %}
					        
						        {% for data in status %}


						  
						        <tr class="success">
						        	<td> {{data.status}} </td>
						            <td style="text-align: right;"> {{data.created_at}} </td>
						            
						        </tr>


						        {% endfor %}

					        {% else %}
					            <div class="alert alert-danger text-center">
					                <strong>There's no status yet.</strong>
					            </div>
					        {% endif %}
					    </tbody>
					</table>
				</div>

			</div>
		</div>
			
		
	</div>

	

</body>